#include <QCoreApplication>
#include "server.h"
#include <gpgme.h>
#include <iostream>
#include <QQueue>

#define detectError(err)                                    \
    if (err) {                                              \
        fprintf (stderr, "%s:%d: %s: %s\n",                 \
                __FILE__, __LINE__, gpgme_strsource (err),  \
                gpgme_strerror (err));                      \
            exit (1);                                       \
        }

QString serverKey(int argc){

    bool validUse=false;
    QString fpr=NULL;

    //Select server key UI loop;
    while(validUse==false){

        if(argc==1){ //User not specify key pair;

            //Create GPGME context and setup GPGME
            gpgme_ctx_t ctx;  // the context
            gpgme_error_t err; // errors
            gpgme_key_t key= nullptr; // the key

            //Begin setup of GPGME
                gpgme_check_version (NULL);
                setlocale (LC_ALL, "");
                gpgme_set_locale (NULL, LC_CTYPE, setlocale (LC_CTYPE, NULL));

                // Create the GPGME Context
                err = gpgme_new (&ctx);
                // Error handling
                detectError(err);

                // Set the context to textmode
                gpgme_set_textmode (ctx, 1);
                // Enable ASCII armor on the context
                gpgme_set_armor (ctx, 1);


            qDebug() << "\n\n-------------------------";
            qDebug() << "Please select option below:\n";
            qDebug() << "G for generate new key pair for server";
            qDebug() << "E for use existing key pair in key ring";

            QTextStream qtin(stdin);
            //QString line = qtin.readLine();

            printf("\nYour selection:");
            QString word;
            qtin >> word;

            if(word=="E" || word=="e"){

                //Loop until user found useable key pair.
                while(true){

                    printf("Enter key fingerprint or key ID:");

                    QTextStream qtin(stdin);
                    //QString line = qtin.readLine();

                    QString word;
                    qtin >> word;

                    QByteArray ba = word.toLatin1();
                    const char *patt=ba.data();

                    err=gpgme_get_key(ctx, patt, &key, 1);

                    qDebug() << "\nGetting private key...";

                    if(key){
                        err=gpgme_get_key(ctx, patt, &key, 0);

                        if(key){
                            fpr=QString(key->fpr);
                            printf("Key ID: %s\n", key->subkeys->keyid);
                            if(key->uids && key->uids->name)
                                printf("Name: %s\n", key->uids->name);
                            if(key->uids && key->uids->email)
                                printf("E-Mail: %s\n\n", key->uids->email);

                            validUse=true;
                            break;
                        }
                        else{
                            qDebug() << "\n\nPublic key not found!!";

                        }
                    }

                    else{
                        qDebug() << "\n\nPrivate key not found!!";
                    }
                }

            }
            if(word=="G" || word=="g"){

                QTextStream qtin(stdin);
                //QString line = qtin.readLine();

                printf("\nChoose name of the new key pair:");
                QString name;
                qtin >> name;

                bool isNameValid=true;

                for(int i=0; i<name.length(); i++){
                    int dec=name.mid(i,1).data()->unicode();
                    char ch=(char)dec;

                }

                QString keyname;
                QString passphrase;

                QString keyParms="<GnupgKeyParms format=\"internal\">\n"
                                 "Key-Type: RSA\n"
                                 "Key-Length: 4096\n"
                                 "Subkey-Type: RSA\n"
                                 "Subkey-Length: 4096\n"
                                 "Name-Real: "+keyname+"\n"
                                 "Name-Comment: Generated by E2EEIM Chat, Passphrase:"+passphrase+"\n"
                                 "Name-Email: server@e2eeim.chat\n"
                                 "Expire-Date: 1y\n"
                                 "Passphrase: "+passphrase+"\n"
                                 "</GnupgKeyParms>\n";

            }
        }
    }
    return fpr;
}

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);

    QQueue<QByteArray> msg;
    QList<QString> usernameList;
    QList<QString> userKeyList;
    QList<QString> loginUser;
    QList<QString> loginRanNum;
    QList<QString> waitingTaskUser;
    QList<QString> waitingTaskWork;
    QList<QString> addFriendRequestList;

    QString keyFpr=serverKey(argc);

    qDebug() << "\n\nkeyFpr:" << keyFpr;

    /*

    //Create server.
    Server server(msg, usernameList, userKeyList, loginUser, loginRanNum, waitingTaskUser, waitingTaskWork, addFriendRequestList);

    //Start server.
    server.startServer();

    */


    // https://forum.qt.io/topic/86025/qt-get-external-ip-address-using-qnetworkreply/2

    return a.exec();
}
